### ISSUE TITLE
Does not work behind proxy?

### ISSUE THREAD

**Issue by copernico** [gingerlime/smugline#19]
I'm trying to make smugline work from behind a corp proxy, but it fails:

```
C:\Users\xxxxxxxxxxx\Desktop\smugline-master>python smugline.py --api-key=**************** list
Email address: ***********@******.com
Password:
Traceback (most recent call last):
  File "smugline.py", line 302, in <module>
    password=arguments['--password'])
  File "smugline.py", line 80, in __init__
    self.login()
  File "smugline.py", line 278, in login
    Password=self.password)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\site-packages\smugpy\__init__.py", line 102, in login_withPassword
    return self._login("login_withPassword", **kwargs)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\site-packages\smugpy\__init__.py", line 91, in _login
    rsp = login(**kwargs)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\site-packages\smugpy\__init__.py", line 197, in api_request
    rsp = self._fetch_url(url, urlencode(kwargs))
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\site-packages\smugpy\__init__.py", line 280, in _fetch_url
    return urlopen(req).read()
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Users\***********\AppData\Local\Continuum\Miniconda2\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by copernico** [comment]
EDIT: urllib2 is able to read environmnent variables, so it is enough to do as follows (in windows):

```
SET http_proxy=<YOURPROXYHERE>:<PROXYPORT>
```
