### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by e40** [gingerlime/smugline#28]
I have the latest from the repo.  I'm getting this.  I uploaded some photos not long ago, and it worked.  Nothing on my side has changed, and my API key and password on the SM side has not, either.

Here's what I'm getting:

    Traceback (most recent call last):
      File "/usr/local/bin/smugline.py", line 315, in <module>
	password=arguments['--password'])
      File "/usr/local/bin/smugline.py", line 86, in __init__
	self.login()
      File "/usr/local/bin/smugline.py", line 291, in login
	Password=self.password)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/smugpy/__init__.py", line 102, in login_withPassword
	return self._login("login_withPassword", **kwargs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/smugpy/__init__.py", line 91, in _login
	rsp = login(**kwargs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/smugpy/__init__.py", line 199, in api_request
	return self._handle_response(rsp)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/smugpy/__init__.py", line 205, in _handle_response
	parsed = json.loads(compat_decode(response))
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
	return _default_decoder.decode(s)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
	obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
	raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

And ideas?

**Comment by e40** [comment]
I just updated my Macports installations.  Same error.  Seems something changed on the SM side that's broken this.  I'm bummed, since I was going to upload some photos for father's day!

**Comment by gingerlime** [comment]
can you post the exact command you're running? (masking any login/password details)

**Comment by e40** [comment]
I got an email from them, after asking them to please turn back on the 1.3 API (they told me it was turned off), for you/us to email api@smugmug.com.  I'm going to do that now.

**Comment by e40** [comment]
At this point, I'm assuming this will never be fixed and this project is dead.

**Comment by gingerlime** [comment]
It looks like this unfortunately... I just don't have the time to rewrite the whole underlying API operations with v2, and I'm not aware of another python API bindings that are flexible enough to convert to use either (even if there was one, it would take considerable time/effort to adapt smugline to it)...

So unfortunately, if SmugMug really deprecated the v1.3 API, then this project will also be practically dead.

**Comment by gingerlime** [comment]
The API team responded

> Beginning on June 11th, the API has required TLS encryption (https). Are your requests being made this way?

It looks like smugpy isn't using https, as far as I can tell ... And as far as I'm aware it's pretty much abandoned at this point.

Not sure I have the time or energy to maintain a fork of smugpy or to port it to v2 etc

Any volunteers??
